import {
  FaBars,
  FaBolt,
  FaBuildingColumns,
  FaBullhorn,
  FaCarSide,
  FaCircleStop,
  FaEnvelope,
  FaEye,
  FaFacebook,
  FaFlagCheckered,
  FaGaugeHigh,
  FaGears,
  FaHandshake,
  FaHandHoldingHeart,
  FaInstagram,
  FaLightbulb,
  FaLinkedin,
  FaLocationDot,
  FaMicrochip,
  FaPhone,
  FaRulerCombined,
  FaShareNodes,
  FaUsers,
  FaUsersGear,
  FaXTwitter
} from "react-icons/fa6";

export const iconMap = {
  faDraftingCompass: FaRulerCombined,
  faCarSide: FaCarSide,
  faBolt: FaBolt,
  faStopCircle: FaCircleStop,
  faMicrochip: FaMicrochip,
  faCogs: FaGears,
  faGaugeHigh: FaGaugeHigh,
  faEye: FaEye,
  faLightbulb: FaLightbulb,
  faShareNodes: FaShareNodes,
  faUsersGear: FaUsersGear,
  faHandHoldingHeart: FaHandHoldingHeart,
  faFlagCheckered: FaFlagCheckered,
  faBullhorn: FaBullhorn,
  faUniversity: FaBuildingColumns,
  faUsers: FaUsers,
  faHandshake: FaHandshake,
  linkedin: FaLinkedin,
  facebook: FaFacebook,
  instagram: FaInstagram,
  x: FaXTwitter,
  FaBars,
  FaPhone,
  FaEnvelope,
  FaLocationDot
};
